### ISSUE TITLE
Group Management in Admin Portal

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/identity-apps#1003]
#### Description

Group management allows you to configure and manage groups. A group contains a set of permissions for a collection of users to manage the server. You can create different groups with various combinations of permissions and assign them to a group of users. Through the admin portal, you can also edit and delete an existing group role.

#### Task List

- [ ] [Support to create a new group](https://github.com/wso2/identity-apps/issues/997)

- [ ] [Add support to edit user groups](https://github.com/wso2/identity-apps/issues/998)

- [ ] [Support to assign a user to a group](https://github.com/wso2/identity-apps/issues/999)

- [ ] [Implement group permission view
](https://github.com/wso2/identity-apps/issues/1000)

- [ ] [Implement group list view](https://github.com/wso2/identity-apps/issues/1001)

- [ ] [Add avatar background to groups list](https://github.com/wso2/identity-apps/issues/1002)
