### ISSUE TITLE
Implement Automation Unit Tests for Developer Portal and Admin Portal with Cypress Test Framework

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/identity-apps#1016]
#### Description

Cypress.io is the UI automation Framework for React. With this effort, automation unit tests will be implemented for the Developer Portal and Admin Portal covering the below main tasks.

#### Task List

- [x] [Implement UI based Unit Tests for Developer Portal Applications Component]()

- [x] [Implement UI based Unit Tests for Developer Portal Identity Provider Component]()

- [x] [Implement UI based Unit Tests for Admin Portal Users Component]()

- [x] [Implement UI based Unit Tests for Admin Portal Roles Component]()

- [x] [Implement UI based Unit Tests for Admin Portal Groups Component]()

- [x] [Implement UI based Unit Tests for Admin Portal Certificate Component]()

- [x] [Implement UI based Unit Tests for Admin Portal Attribute Dialect Component]()

- [x] [Implement UI based Unit Tests for Admin Portal UserStores Component]()

- [x] [Implement UI based Unit Tests for Admin Portal Configurations Component]()
