### ISSUE TITLE
IDP Management in Admin Portal

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/identity-apps#983]
### Description

IDP management involves creating and managing identity providers in the system. The IDP management feature in the admin portal provides system administrators with a high-level view of currently existing IDPs, functionalities of each IDP, and their properties in the system. It enables system admins to make business-critical, real-time security decisions.

- [x] [Identity Provider Management - Configure Resident IDP](https://github.com/wso2/identity-apps/issues/363)
- [x] [Identity Provider Management - Design an info view for Identity Providers.](https://github.com/wso2/identity-apps/issues/361)
- [x] [Identity Provider Management - Implement advance search options for the identity providers list](https://github.com/wso2/identity-apps/issues/353)
- [x] [Identity Provider Management - Implement identity providers list sorting & filtering.](https://github.com/wso2/identity-apps/issues/352)
- [x] [Identity Provider Management - Create basic list view.](https://github.com/wso2/identity-apps/issues/351)
- [x] [Add localization support for IDP management](https://github.com/wso2/identity-apps/issues/992)

**Comment by vihanga-liyanage** [comment]
Duplicate: https://github.com/wso2/identity-apps/issues/354
