### ISSUE TITLE
Application Management in Developer Portal

### ISSUE THREAD

**Issue by brionmario** [wso2/identity-apps#984]
**Description:**
WSO2 Identity Server (WSO2 IS) allows you to configure and manage applications(Service Providers). The Application Management feature in the Developer Portal should enable users to:
1. Define how the application talks to the Identity Server .
2. Define how to authenticate users.
3. Maintain claim mapping.

Developer Portal should consume the new [Application Management Rest API](https://is.docs.wso2.com/en/latest/develop/application-rest-api/#/application-management-rest-api-definition-v1) to interface with the Identity Server.

**Tasks:**
The following are the main tasks that has been identified.

- [x] [Create a basic list view to display applications](https://github.com/wso2/identity-apps/issues/322)
- [x] [Implement applications list sorting & filtering](https://github.com/wso2/identity-apps/issues/337)
- [x] [Implement Provisioning configurations in Applications](https://github.com/wso2/identity-apps/issues/335)
- [x] [Implement sign on method configuration in Applications](https://github.com/wso2/identity-apps/issues/333)
- [x] [Implement Governance Configuration in Applcations](https://github.com/wso2/identity-apps/issues/338)
- [x] [Implement advance search options for the applications list (search by name)](https://github.com/wso2/identity-apps/issues/512)
- [x] [Add ability to create a basic application from Developer Portal](https://github.com/wso2/identity-apps/issues/342)
- [x] [Add ability to configure application claims](https://github.com/wso2/identity-apps/issues/343)
- [x] [Add ability configure inbound authentication for applications](https://github.com/wso2/identity-apps/issues/345)
- [x] [Add ability to configure roles & permissions for an application](https://github.com/wso2/identity-apps/issues/344)
- [x] [Implement Application update capability](https://github.com/wso2/identity-apps/issues/380)
- [x] [Add localization support to Application management section](https://github.com/wso2/identity-apps/issues/384)
- [x] [Implement capability to create applications using predefined templates](https://github.com/wso2/identity-apps/issues/585)
- [x] [Need a template to create Windows desktop applications
](https://github.com/wso2/identity-apps/issues/695)
- [x] [Add help panel to assist the users while working with Applications in Developer Portal
](https://github.com/wso2/identity-apps/issues/593)
