### ISSUE TITLE
Role Management in Admin Portal

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/identity-apps#996]
#### Description

Role management allows you to configure and manage roles as well as permission for a service provider. Roles contain permissions for users to manage the server. You can create different roles with various combinations of permissions and assign them to a user or a group of users. Through the admin portal, you can also edit and delete an existing user role.

#### Task List

- [ ] [Support to create new role](https://github.com/wso2/identity-apps/issues/324)

- [ ] [Add support to edit user roles](https://github.com/wso2/identity-apps/issues/327)

- [ ] [Support to assign a user to a role](https://github.com/wso2/identity-apps/issues/325)

- [ ] [Implement role permission view](https://github.com/wso2/identity-apps/issues/328)

- [ ] [Add permission tree view](https://github.com/wso2/identity-apps/issues/326)

- [ ] [Implement role list view](https://github.com/wso2/identity-apps/issues/320)

- [ ] [Add avatar background to roles list
](https://github.com/wso2/identity-apps/issues/737)
